name: publish workflow
on:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Release Type - major, minor, or patch'
        required: true
        default: 'patch'
        options:
          - major
          - minor
          - patch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
       - name: Verify version type input
         run: |
           echo "Input version type: ${{ github.event.inputs.versionType }}"
       - name: Echo test
         run: |
           echo "publish ont est branch" 
